import React, { useState } from "react";
import { Link } from "react-router-dom";
import SEO from "../components/common/SEO";
import TechnicalGuidesNav from "../components/common/TechnicalGuidesNav";
import FAQSection from "../components/common/FAQSection";
import HomeCTA from "../components/home/HomeCTA";

export default function SelectionGuide() {
  // Calculator state
  const [machineModel, setMachineModel] = useState("nord-super-simplex");
  const [webWidth, setWebWidth] = useState(1300);
  const [lineSpeed, setLineSpeed] = useState(350);
  const [adhesiveType, setAdhesiveType] = useState("2k-pu");

  // Dynamic recommendations
  const getRecommendation = () => {
    let materialGrade = "Virgin Food-Grade PTFE (White)";
    let hardness = "55 - 60 Shore D";
    let frictionCoeff = "0.04 - 0.08 (Ultra-Low)";
    let bevelProfile = "Double Concave Radial Arc (R125 / R140)";
    let clampingForce = "1.8 - 2.2 bar (pneumatic) / Finger-tight + 1/4 turn";
    let estLife = "6 - 9 months continuous production";
    let notes = "Ideal for standard flexible food packaging laminations at speeds up to 400 m/min.";

    if (machineModel === "bobst-lamination") {
      bevelProfile = "Precision Bobst Offset Arc with Step-Lip";
    } else if (machineModel === "uteco-rainbow") {
      bevelProfile = "Uteco Symmetric Concave Channel Profile";
    } else if (machineModel === "comexi-nexus") {
      bevelProfile = "Comexi Narrow-Nip Dual Radial Chamfer";
    }

    if (lineSpeed > 400 || adhesiveType === "solvent-based") {
      materialGrade = "15% Glass-Filled PTFE (Off-White / Beige)";
      hardness = "62 - 68 Shore D";
      frictionCoeff = "0.06 - 0.10";
      estLife = "9 - 14 months high-speed resistance";
      notes = "Higher rigidity and compressive creep resistance. Prevents thermal edge deformation at speeds exceeding 400 m/min.";
    }

    if (adhesiveType === "uv-curable") {
      materialGrade = "Carbon/Graphite-Filled Antistatic PTFE (Black)";
      hardness = "65 - 70 Shore D";
      frictionCoeff = "0.05 - 0.09";
      notes = "Dissipates static charges generated by high-speed dry-nip friction while preventing photo-initiated adhesive polymerization along the dam edge.";
    }

    return {
      materialGrade,
      hardness,
      frictionCoeff,
      bevelProfile,
      clampingForce,
      estLife,
      notes,
    };
  };

  const rec = getRecommendation();

  // FAQ Schema
  const faqs = [
    {
      question: "How do I choose between Virgin PTFE and Glass-Filled Teflon for my dam?",
      answer: "Virgin PTFE (pure white) is the industry benchmark for standard flexible food packaging run on Nordmeccanica, Bobst, and Comexi machines up to 380-400 m/min. If your lines run continuously at 400 to 500+ m/min, or if you run abrasive or high-viscosity coatings, 15% Glass-Filled PTFE is recommended because it resists thermal deflection and edge creep under prolonged friction.",
    },
    {
      question: "Can I use one universal Teflon Dam across all my lamination machines?",
      answer: "No. Teflon Dams are strictly machine-specific. Nordmeccanica Super Simplex, Super Combi, Bobst CL 750, and Comexi machines each use different roller diameters (e.g. chrome metering roll vs. rubber transfer roll), different center-to-center distances, and distinct bracket mounts. Using an incorrect radius profile causes adhesive to seep under the dam and score expensive steel rollers.",
    },
    {
      question: "How tight should the Teflon Dam clamping bracket be adjusted?",
      answer: "Teflon dams should never be forced excessively against the rotating rollers. Apply gentle, uniform pressure: if mechanical, tighten finger-tight plus one-quarter turn; if pneumatic, set to 1.5 to 2.2 bar. Over-tightening causes frictional heat, premature Teflon softening, and excessive wear on roll rubber coverings.",
    },
    {
      question: "What measurements do I need to supply for a custom Teflon Dam?",
      answer: "For custom machines, you need: 1) Metering roller outer diameter, 2) Transfer/application roller outer diameter, 3) Inter-roller nip gap at zero setting, 4) Desired dam thickness (typically 15mm, 18mm, or 20mm), and 5) Mounting bracket slot dimensions or an existing sample for CNC digitizing.",
    },
    {
      question: "How does proper Teflon Dam sizing prevent adhesive edge oozing?",
      answer: "A precision-machined dam provides a micro-tolerance seal that matches the true cylindrical curvature of the counter-rotating rollers. When the curvature is exact, adhesive meniscus tension stays inside the metering reservoir without weeping out the side flanks, eliminating adhesive build-up on web edges.",
    },
  ];

  const breadcrumbs = [
    { name: "Home", item: "https://www.teflondam.com/" },
    { name: "Technical Guides", item: "https://www.teflondam.com/selection-guide" },
    { name: "Selection & Sizing Guide", item: "https://www.teflondam.com/selection-guide" },
  ];

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    headline: "Teflon Dam Selection & Sizing Guide for Solventless Lamination Machines",
    description: "Complete engineering guide to sizing, measuring, and selecting precision PTFE Teflon Dams for solventless laminators including Nord, Bobst, Uteco, and Comexi.",
    image: "https://www.teflondam.com/heroimage.webp",
    author: {
      "@type": "Organization",
      name: "ImageTech Industries",
    },
    publisher: {
      "@type": "Organization",
      name: "ImageTech Industries",
      logo: {
        "@type": "ImageObject",
        url: "https://www.teflondam.com/logo.png",
      },
    },
    mainEntityOfPage: "https://www.teflondam.com/selection-guide",
  };

  const howToSchema = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: "How to Measure and Size a Teflon Dam for a Solventless Lamination Machine",
    description: "Three simple pressroom steps to accurately measure and verify Teflon Dam dimensions for your laminator.",
    step: [
      {
        "@type": "HowToStep",
        name: "Step 1: Check Roller Outer Diameter and Nip Clearance",
        text: "Measure the exact outer diameter of both the chrome metering roller and the rubber applicator roller using a vernier caliper or circumference tape.",
      },
      {
        "@type": "HowToStep",
        name: "Step 2: Trace or Measure the Radial Bevel Curvature",
        text: "Verify the concave arc radius where the dam contacts each roller. The curve must precisely correspond to roll radius to prevent liquid adhesive leakage.",
      },
      {
        "@type": "HowToStep",
        name: "Step 3: Measure the Side Bracket Clamping Thickness",
        text: "Measure the thickness of the dam base (typically 12mm, 15mm, 18mm, or 20mm) and slot width to confirm drop-in compatibility with your machine's side dam holder.",
      },
    ],
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: f.answer,
      },
    })),
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: breadcrumbs.map((b, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: b.name,
      item: b.item,
    })),
  };

  return (
    <>
      <SEO
        title="Teflon Dam Selection & Sizing Guide | PTFE Dam Manufacturer"
        description="Comprehensive Teflon Dam selection and sizing guide for solventless lamination machines. Sizing calculator, PTFE grade tolerance matrix, and 3-step measurement guide by ImageTech Industries."
        keywords={[
          "teflon dam selection guide",
          "teflon dam sizing guide",
          "teflon dam manufacturer & exporter",
          "teflon dam dimensions",
          "how to measure teflon dam",
          "nord super simplex teflon dam sizing",
          "bobst teflon dam size",
          "uteco teflon dam measurements",
          "ptfe dam tolerances",
          "solventless lamination accessories",
          "imagetech industries",
        ]}
        schema={[articleSchema, howToSchema, faqSchema, breadcrumbSchema]}
      />

      <main className="bg-slate-50 min-h-screen">
        {/* Breadcrumb Bar above Technical Guides Nav */}
        <div className="bg-white border-b border-slate-100 py-2.5">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <nav className="flex items-center text-xs font-semibold text-slate-500 flex-wrap gap-1.5">
              <Link to="/" className="hover:text-blue-600 transition-colors">Home</Link>
              <span>/</span>
              <span className="text-slate-400">Technical Guides</span>
              <span>/</span>
              <span className="text-blue-600 font-bold">Selection & Sizing Guide</span>
            </nav>
          </div>
        </div>

        {/* Sticky Sub-Nav */}
        <TechnicalGuidesNav />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-10 space-y-10 sm:space-y-12 w-full">
          {/* Centered Page Heading Section */}
          <div className="border-b border-slate-200/80 pb-6 sm:pb-8 text-center max-w-4xl mx-auto">
            <h1 className="text-2xl sm:text-3xl lg:text-4xl font-black text-slate-900 tracking-tight leading-tight mb-2">
              Teflon Dam <span className="text-blue-600">Selection & Sizing Guide</span> for Solventless Lamination
            </h1>

            <p className="text-sm sm:text-base text-slate-600 leading-relaxed max-w-3xl mx-auto font-medium">
              The authoritative engineering resource for selecting, sizing, and verifying high-precision PTFE containment dams. Discover exact dimensions for Nordmeccanica, Bobst, Uteco, and Comexi machines, use our interactive calculator, and avoid adhesive edge-leakage on high-speed converting runs.
            </p>
          </div>
          {/* SECTION 1: Interactive Sizing Calculator */}
          <section className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 pb-6 border-b border-slate-100">
              <div>
                <span className="text-xs font-black uppercase tracking-widest text-blue-600 block mb-1">
                  Engineering Calculator
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
                  Interactive Teflon Dam Sizing Tool
                </h2>
                <p className="text-slate-600 text-sm mt-1">
                  Select your machine parameters to calculate the optimal dam profile, material grade, and clamping settings.
                </p>
              </div>

              <div className="shrink-0">
                <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-emerald-50 text-emerald-700 text-xs font-bold rounded-full border border-emerald-200">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  Live Pressroom Model
                </span>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              {/* Calculator Inputs */}
              <div className="lg:col-span-6 space-y-5 bg-slate-50 p-6 rounded-2xl border border-slate-200/80">
                {/* Machine Model */}
                <div>
                  <label className="block text-xs font-black uppercase tracking-wider text-slate-700 mb-2">
                    1. Machine Model / Manufacturer
                  </label>
                  <select
                    value={machineModel}
                    onChange={(e) => setMachineModel(e.target.value)}
                    className="w-full bg-white border border-slate-300 rounded-xl px-4 py-3 text-sm font-semibold text-slate-800 focus:outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-600/15"
                  >
                    <option value="nord-super-simplex">Nordmeccanica Super Simplex (Standard R125/R140)</option>
                    <option value="nord-super-combi">Nordmeccanica Super Combi 3000 / 4000</option>
                    <option value="bobst-lamination">Bobst CL 750 / SL 1000 Solventless</option>
                    <option value="uteco-rainbow">Uteco Rainbow / Horizon Converting</option>
                    <option value="comexi-nexus">Comexi Nexus Dual / SL2</option>
                    <option value="custom-machine">Custom Converting / Coating Machine</option>
                  </select>
                </div>

                {/* Line Speed */}
                <div>
                  <div className="flex justify-between text-xs font-black uppercase tracking-wider text-slate-700 mb-2">
                    <span>2. Average Line Speed</span>
                    <span className="text-blue-600 font-bold">{lineSpeed} m/min</span>
                  </div>
                  <input
                    type="range"
                    min="100"
                    max="600"
                    step="25"
                    value={lineSpeed}
                    onChange={(e) => setLineSpeed(Number(e.target.value))}
                    className="w-full accent-blue-600 cursor-pointer"
                  />
                  <div className="flex justify-between text-[11px] text-slate-400 font-semibold mt-1">
                    <span>100 m/min (Standard)</span>
                    <span>350 m/min (Average)</span>
                    <span>600 m/min (High-Speed)</span>
                  </div>
                </div>

                {/* Web Width */}
                <div>
                  <div className="flex justify-between text-xs font-black uppercase tracking-wider text-slate-700 mb-2">
                    <span>3. Roller Face / Web Width</span>
                    <span className="text-blue-600 font-bold">{webWidth} mm</span>
                  </div>
                  <input
                    type="range"
                    min="800"
                    max="1800"
                    step="50"
                    value={webWidth}
                    onChange={(e) => setWebWidth(Number(e.target.value))}
                    className="w-full accent-blue-600 cursor-pointer"
                  />
                  <div className="flex justify-between text-[11px] text-slate-400 font-semibold mt-1">
                    <span>800 mm</span>
                    <span>1300 mm (Standard)</span>
                    <span>1800 mm (Wide-Web)</span>
                  </div>
                </div>

                {/* Adhesive Chemistry */}
                <div>
                  <label className="block text-xs font-black uppercase tracking-wider text-slate-700 mb-2">
                    4. Adhesive / Coating Chemistry
                  </label>
                  <select
                    value={adhesiveType}
                    onChange={(e) => setAdhesiveType(e.target.value)}
                    className="w-full bg-white border border-slate-300 rounded-xl px-4 py-3 text-sm font-semibold text-slate-800 focus:outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-600/15"
                  >
                    <option value="2k-pu">2-Component Polyurethane (Standard Solventless)</option>
                    <option value="1k-pu">1-Component Moisture-Curing Polyurethane</option>
                    <option value="solvent-based">Solvent-Based Ethyl Acetate Adhesives</option>
                    <option value="uv-curable">UV-Curable / 100% Solid Monomer Adhesives</option>
                  </select>
                </div>
              </div>

              {/* Calculator Results Card */}
              <div className="lg:col-span-6 bg-gradient-to-br from-blue-50/70 via-white to-slate-50 p-6 sm:p-8 rounded-2xl border-2 border-blue-200 shadow-md">
                <div className="flex items-center justify-between pb-4 border-b border-blue-100 mb-6">
                  <div>
                    <span className="text-[11px] font-black uppercase tracking-widest text-blue-700">
                      Recommended Specification
                    </span>
                    <h3 className="text-xl font-black text-slate-900 mt-0.5">
                      Engineered Dam Configuration
                    </h3>
                  </div>
                  <span className="px-3 py-1 bg-blue-600 text-white text-xs font-bold rounded-lg shadow-sm">
                    Verified Fit
                  </span>
                </div>

                <div className="space-y-4 text-sm">
                  <div className="flex justify-between items-start pb-3 border-b border-slate-200/60">
                    <span className="font-bold text-slate-600">Material Grade:</span>
                    <span className="font-extrabold text-blue-700 text-right max-w-[60%]">
                      {rec.materialGrade}
                    </span>
                  </div>

                  <div className="flex justify-between items-center pb-3 border-b border-slate-200/60">
                    <span className="font-bold text-slate-600">Shore Hardness:</span>
                    <span className="font-extrabold text-slate-900">{rec.hardness}</span>
                  </div>

                  <div className="flex justify-between items-center pb-3 border-b border-slate-200/60">
                    <span className="font-bold text-slate-600">Kinetic Friction Coeff:</span>
                    <span className="font-extrabold text-slate-900">{rec.frictionCoeff}</span>
                  </div>

                  <div className="flex justify-between items-start pb-3 border-b border-slate-200/60">
                    <span className="font-bold text-slate-600">Bevel & Arc Geometry:</span>
                    <span className="font-extrabold text-slate-900 text-right max-w-[60%]">
                      {rec.bevelProfile}
                    </span>
                  </div>

                  <div className="flex justify-between items-start pb-3 border-b border-slate-200/60">
                    <span className="font-bold text-slate-600">Optimal Clamping Force:</span>
                    <span className="font-extrabold text-slate-900 text-right max-w-[60%]">
                      {rec.clampingForce}
                    </span>
                  </div>

                  <div className="flex justify-between items-center pb-3 border-b border-slate-200/60">
                    <span className="font-bold text-slate-600">Expected Pressroom Life:</span>
                    <span className="font-extrabold text-emerald-700">{rec.estLife}</span>
                  </div>

                  <div className="pt-2">
                    <p className="text-xs text-slate-600 bg-white p-3 rounded-xl border border-blue-100 font-medium leading-relaxed">
                      <strong className="text-slate-900 font-bold">Engineering Note:</strong> {rec.notes}
                    </p>
                  </div>
                </div>

                <div className="mt-6 pt-4 flex flex-col sm:flex-row gap-3">
                  <button
                    onClick={() => window.dispatchEvent(new CustomEvent("open-quote-modal"))}
                    className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-bold text-sm py-3 px-5 rounded-xl transition-all shadow-md shadow-blue-600/20 text-center flex items-center justify-center cursor-pointer"
                  >
                    Request Custom Quote for this Spec →
                  </button>
                  <a
                    href="tel:+918448336036"
                    className="bg-white hover:bg-slate-50 text-slate-800 border border-slate-300 font-bold text-sm py-3 px-4 rounded-xl transition-colors text-center"
                  >
                    Call Engineer
                  </a>
                </div>
              </div>
            </div>
          </section>

          {/* SECTION 2: How to Measure in 3 Simple Steps */}
          <section className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm">
            <div className="text-center max-w-3xl mx-auto mb-10">
              <span className="text-xs font-black uppercase tracking-widest text-blue-600">
                Pressroom Standard Operating Procedure
              </span>
              <h2 className="text-2xl sm:text-3xl lg:text-4xl font-black text-slate-900 tracking-tight mt-1">
                How to Measure Your Machine Rollers in 3 Simple Steps
              </h2>
              <p className="text-slate-600 text-sm sm:text-base mt-3 leading-relaxed">
                You do not need to tear down your lamination head to get exact replacement Teflon dams. Use this simple operator procedure with basic tools.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {/* Step 1 */}
              <div className="bg-slate-50 rounded-2xl p-6 border border-slate-200 relative flex flex-col">
                <div className="w-10 h-10 rounded-full bg-blue-600 text-white font-black text-lg flex items-center justify-center mb-5 shadow-md shadow-blue-600/25">
                  1
                </div>
                <h3 className="text-lg font-bold text-slate-900 mb-2">
                  Check Roller Diameters & Gap
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed mb-4 flex-grow">
                  Using a vernier caliper or circumference pi-tape, measure the outer diameter (OD) of the steel/chrome metering roll and the rubber applicator roll. Note the zero-gap position between the two cylinders.
                </p>
                <div className="text-xs bg-white p-3 rounded-xl border border-slate-200 text-slate-700 font-semibold">
                  <strong>Standard Range:</strong> Ø120 mm to Ø240 mm metering rolls.
                </div>
              </div>

              {/* Step 2 */}
              <div className="bg-slate-50 rounded-2xl p-6 border border-slate-200 relative flex flex-col">
                <div className="w-10 h-10 rounded-full bg-blue-600 text-white font-black text-lg flex items-center justify-center mb-5 shadow-md shadow-blue-600/25">
                  2
                </div>
                <h3 className="text-lg font-bold text-slate-900 mb-2">
                  Trace or Gauge Bevel Arc Radius
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed mb-4 flex-grow">
                  Place a radius gauge or cardboard template against the side of the existing worn dam. Measure the concave arc that sits flush against each roll face. An exact curvature prevents adhesive seepage under the dam.
                </p>
                <div className="text-xs bg-white p-3 rounded-xl border border-slate-200 text-slate-700 font-semibold">
                  <strong>Standard Radius:</strong> R125 / R140 for Nordmeccanica Simplex.
                </div>
              </div>

              {/* Step 3 */}
              <div className="bg-slate-50 rounded-2xl p-6 border border-slate-200 relative flex flex-col">
                <div className="w-10 h-10 rounded-full bg-blue-600 text-white font-black text-lg flex items-center justify-center mb-5 shadow-md shadow-blue-600/25">
                  3
                </div>
                <h3 className="text-lg font-bold text-slate-900 mb-2">
                  Measure Bracket Slot & Thickness
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed mb-4 flex-grow">
                  Measure the thickness of the dam body (typically 15mm, 18mm, or 20mm) and the width of the mounting groove or bolt holes that slide into the machine's side holder bracket.
                </p>
                <div className="text-xs bg-white p-3 rounded-xl border border-slate-200 text-slate-700 font-semibold">
                  <strong>Standard Thickness:</strong> 15mm, 18mm, or 20mm CNC-machined.
                </div>
              </div>
            </div>
          </section>

          {/* SECTION 3: Material Grade Matrix */}
          <section className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm overflow-hidden">
            <div className="mb-8">
              <span className="text-xs font-black uppercase tracking-widest text-blue-600">
                PTFE Polymer Science
              </span>
              <h2 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight mt-1">
                PTFE Material Grade & Chemical Tolerance Matrix
              </h2>
              <p className="text-slate-600 text-sm sm:text-base mt-2">
                ImageTech Teflon Dams are machined from certified compression-molded virgin and filled PTFE grades. Review their technical properties to match your converting environment.
              </p>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm border-collapse min-w-[650px]">
                <thead>
                  <tr className="bg-slate-100 border-b border-slate-200 text-slate-800 text-xs uppercase font-extrabold tracking-wider">
                    <th className="py-3.5 px-4">PTFE Grade</th>
                    <th className="py-3.5 px-4">Color</th>
                    <th className="py-3.5 px-4">Shore Hardness</th>
                    <th className="py-3.5 px-4">Max Temp</th>
                    <th className="py-3.5 px-4">Friction Coeff</th>
                    <th className="py-3.5 px-4">Best Press Application</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-slate-700 font-medium">
                  <tr className="hover:bg-blue-50/50 transition-colors">
                    <td className="py-4 px-4 font-bold text-slate-900">Virgin PTFE (Grade A)</td>
                    <td className="py-4 px-4">Pure White</td>
                    <td className="py-4 px-4">55 - 60 Shore D</td>
                    <td className="py-4 px-4">260°C (500°F)</td>
                    <td className="py-4 px-4">0.04 - 0.08</td>
                    <td className="py-4 px-4">Flexible food packaging, general 2K solventless lamination up to 400 m/min.</td>
                  </tr>
                  <tr className="hover:bg-blue-50/50 transition-colors">
                    <td className="py-4 px-4 font-bold text-slate-900">15% Glass-Filled PTFE</td>
                    <td className="py-4 px-4">Beige / Off-White</td>
                    <td className="py-4 px-4">62 - 68 Shore D</td>
                    <td className="py-4 px-4">270°C</td>
                    <td className="py-4 px-4">0.06 - 0.10</td>
                    <td className="py-4 px-4">High-speed presses (450+ m/min), heavy abrasive nip pressures, long continuous campaigns.</td>
                  </tr>
                  <tr className="hover:bg-blue-50/50 transition-colors">
                    <td className="py-4 px-4 font-bold text-slate-900">Carbon/Graphite PTFE</td>
                    <td className="py-4 px-4">Matte Black</td>
                    <td className="py-4 px-4">65 - 70 Shore D</td>
                    <td className="py-4 px-4">280°C</td>
                    <td className="py-4 px-4">0.05 - 0.09</td>
                    <td className="py-4 px-4">Antistatic requirements, UV curing coatings, dry-friction thermal dissipation.</td>
                  </tr>
                  <tr className="hover:bg-blue-50/50 transition-colors">
                    <td className="py-4 px-4 font-bold text-slate-900">Bronze-Filled PTFE</td>
                    <td className="py-4 px-4">Bronze-Brown</td>
                    <td className="py-4 px-4">70 - 75 Shore D</td>
                    <td className="py-4 px-4">260°C</td>
                    <td className="py-4 px-4">0.08 - 0.12</td>
                    <td className="py-4 px-4">Extreme compressive load industrial coating heads, specialty hot-melt lamination.</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          {/* SECTION 4: Machine Compatibility Matrix */}
          <section className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm">
            <div className="mb-8">
              <span className="text-xs font-black uppercase tracking-widest text-blue-600">
                Machine Dimension Reference
              </span>
              <h2 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight mt-1">
                Standard Machine-Specific Dam Models
              </h2>
              <p className="text-slate-600 text-sm mt-2">
                We manufacture ready-to-dispatch machine-specific Teflon Dams for the industry’s most popular solventless laminators.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 flex flex-col justify-between">
                <div>
                  <span className="text-[10px] font-black uppercase tracking-wider text-blue-600 bg-blue-50 px-2 py-0.5 rounded-md border border-blue-200">
                    Nordmeccanica
                  </span>
                  <h3 className="font-extrabold text-base text-slate-900 mt-2 mb-2">
                    Super Simplex & Super Combi
                  </h3>
                  <p className="text-xs text-slate-600 leading-relaxed mb-4">
                    Precision radial bevel to match the counter-rotating chrome and NBR rubber roll profiles. Drop-in replacement for Nord quick-change brackets.
                  </p>
                </div>
                <Link
                  to="/products/teflon-dam-for-nord-super-simplex-and-super-combi"
                  className="text-xs font-bold text-blue-600 hover:text-blue-800 flex items-center"
                >
                  View Nord Model →
                </Link>
              </div>

              <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 flex flex-col justify-between">
                <div>
                  <span className="text-[10px] font-black uppercase tracking-wider text-blue-600 bg-blue-50 px-2 py-0.5 rounded-md border border-blue-200">
                    Bobst
                  </span>
                  <h3 className="font-extrabold text-base text-slate-900 mt-2 mb-2">
                    Bobst CL 750 & SL 1000
                  </h3>
                  <p className="text-xs text-slate-600 leading-relaxed mb-4">
                    Tailored side dam geometry engineered for Bobst precision micro-gap coating units. Prevents edge adhesive build-up during long continuous shifts.
                  </p>
                </div>
                <Link
                  to="/products/teflon-dam-for-bobst"
                  className="text-xs font-bold text-blue-600 hover:text-blue-800 flex items-center"
                >
                  View Bobst Model →
                </Link>
              </div>

              <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 flex flex-col justify-between">
                <div>
                  <span className="text-[10px] font-black uppercase tracking-wider text-blue-600 bg-blue-50 px-2 py-0.5 rounded-md border border-blue-200">
                    Uteco
                  </span>
                  <h3 className="font-extrabold text-base text-slate-900 mt-2 mb-2">
                    Uteco Rainbow & Horizon
                  </h3>
                  <p className="text-xs text-slate-600 leading-relaxed mb-4">
                    Specifically contoured for Uteco solventless coating units. High dimensional stability ensures uniform adhesive coating weight out to the film edge.
                  </p>
                </div>
                <Link
                  to="/products/teflon-dam-for-uteco"
                  className="text-xs font-bold text-blue-600 hover:text-blue-800 flex items-center"
                >
                  View Uteco Model →
                </Link>
              </div>

              <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 flex flex-col justify-between">
                <div>
                  <span className="text-[10px] font-black uppercase tracking-wider text-blue-600 bg-blue-50 px-2 py-0.5 rounded-md border border-blue-200">
                    Comexi
                  </span>
                  <h3 className="font-extrabold text-base text-slate-900 mt-2 mb-2">
                    Comexi Nexus SL2 & Dual
                  </h3>
                  <p className="text-xs text-slate-600 leading-relaxed mb-4">
                    Engineered to withstand Comexi high-speed nip dynamics. Superior resistance to 2-component polyurethane resins and cleaning solvents.
                  </p>
                </div>
                <Link
                  to="/products/teflon-dam-for-comexi"
                  className="text-xs font-bold text-blue-600 hover:text-blue-800 flex items-center"
                >
                  View Comexi Model →
                </Link>
              </div>
            </div>
          </section>

          {/* SECTION 5: Pressroom Tooling Checklist: Doctor Blades & Teflon Dams */}
          <section className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm">
            <div className="max-w-3xl mb-8">
              <span className="text-xs font-black uppercase tracking-widest text-blue-600">
                Pressroom Tooling Calibration
              </span>
              <h2 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight mt-1">
                Doctor Blade & Teflon Dam Sizing Checklist
              </h2>
              <p className="text-slate-600 text-sm sm:text-base mt-2">
                When commissioning a flexible packaging run, top converters verify both transverse wiping (<strong>doctor blades</strong>) and axial edge sealing (<strong>Teflon dams</strong>) together. Use this 4-point press checklist to prevent leaks and web defects before starting the line.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
              {/* Point 1 */}
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200">
                <div className="flex items-center gap-3 mb-3">
                  <span className="w-8 h-8 rounded-lg bg-blue-600 text-white font-bold flex items-center justify-center text-sm">
                    01
                  </span>
                  <h3 className="font-extrabold text-base text-slate-900">
                    Verify Reground Roll Diameters
                  </h3>
                </div>
                <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mb-3 font-medium">
                  Whenever metering or applicator rolls undergo grinding or re-chroming, their outer diameter shrinks by 0.5 to 1.5 mm. Using an old Teflon dam on a reground cylinder creates a micro-wedge gap that leaks adhesive immediately.
                </p>
                <div className="text-xs text-blue-900 font-bold bg-blue-50 p-3 rounded-xl border border-blue-100">
                  Action: Always measure roll circumference with a π-tape before ordering replacement dams.
                </div>
              </div>

              {/* Point 2 */}
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200">
                <div className="flex items-center gap-3 mb-3">
                  <span className="w-8 h-8 rounded-lg bg-blue-600 text-white font-bold flex items-center justify-center text-sm">
                    02
                  </span>
                  <h3 className="font-extrabold text-base text-slate-900">
                    Synchronize Doctor Blade & Dam Edge Margins
                  </h3>
                </div>
                <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mb-3 font-medium">
                  For gravure coating and flexo priming, the doctor blade must oscillate smoothly without touching or clipping the stationary Teflon side dam. Maintain a minimum 5 mm safe lateral clearance between blade edge and dam inner face.
                </p>
                <div className="text-xs text-blue-900 font-bold bg-blue-50 p-3 rounded-xl border border-blue-100">
                  Action: Check oscillation stroke amplitude (typically 8–12 mm) during dry-run setup.
                </div>
              </div>

              {/* Point 3 */}
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200">
                <div className="flex items-center gap-3 mb-3">
                  <span className="w-8 h-8 rounded-lg bg-blue-600 text-white font-bold flex items-center justify-center text-sm">
                    03
                  </span>
                  <h3 className="font-extrabold text-base text-slate-900">
                    Pneumatic Clamping Alignment
                  </h3>
                </div>
                <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mb-3 font-medium">
                  Uneven side pressure tilts the dam, causing the inner edge to bite into rubber sleeves while the outer edge gaps and leaks adhesive. Calibrate dual pneumatic cylinders to ensure identical 1.5–2.0 bar pressure on operator and drive sides.
                </p>
                <div className="text-xs text-blue-900 font-bold bg-blue-50 p-3 rounded-xl border border-blue-100">
                  Action: Test face contact using a 0.03 mm feeler gauge with rolls stationary.
                </div>
              </div>

              {/* Point 4 */}
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200">
                <div className="flex items-center gap-3 mb-3">
                  <span className="w-8 h-8 rounded-lg bg-blue-600 text-white font-bold flex items-center justify-center text-sm">
                    04
                  </span>
                  <h3 className="font-extrabold text-base text-slate-900">
                    Chemical & Solvent Compatibility
                  </h3>
                </div>
                <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mb-3 font-medium">
                  Verify whether your application uses solventless polyurethane, solvent-based ethyl acetate inks, or water-based acrylics. Pure virgin PTFE Teflon is universally resistant to 100% of converting chemicals and cleaning solvents.
                </p>
                <div className="text-xs text-blue-900 font-bold bg-blue-50 p-3 rounded-xl border border-blue-100">
                  Action: Clean exclusively with brass scrapers and ethyl acetate; avoid aggressive steel knives.
                </div>
              </div>
            </div>
          </section>

          {/* SECTION 6: CNC Machined PTFE vs 3D-Printed / Hand-Cut Seals */}
          <section className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm overflow-hidden">
            <div className="mb-8 max-w-3xl">
              <span className="text-xs font-black uppercase tracking-widest text-blue-600">
                Manufacturing Quality Standards
              </span>
              <h2 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight mt-1">
                ImageTech 5-Axis CNC PTFE vs. 3D-Printed & Hand-Cut Seals
              </h2>
              <p className="text-slate-600 text-sm mt-2">
                Why pressrooms that attempt to 3D-print or hand-saw side dams suffer chronic leaks, scored cylinders, and thousands in wasted adhesive.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
              {/* Hand Cut */}
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-black uppercase tracking-wider text-red-600 bg-red-50 px-2.5 py-1 rounded-md border border-red-200">
                      High Failure Risk
                    </span>
                    <span className="text-xs text-slate-400 font-bold">Hand-Cut Felt / UHMW</span>
                  </div>
                  <h3 className="font-extrabold text-lg text-slate-900 mb-2">
                    Hand-Sawn / Felt Blocks
                  </h3>
                  <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mb-4">
                    Cut with hacksaws or bandsaws in pressroom workshops. Hand filing produces irregular radii with 0.5–1.0 mm gaps. Felt fibers soak up glue, dry hard, and act like coarse sandpaper against spinning rolls.
                  </p>
                </div>
                <ul className="text-xs space-y-2 text-red-700 font-semibold border-t border-slate-200 pt-4">
                  <li>✕ Dimensional tolerance: ±1.00 mm (Loose fit)</li>
                  <li>✕ Service life: 3 to 10 days</li>
                  <li>✕ Scores chrome cylinders & destroys rubber sleeves</li>
                </ul>
              </div>

              {/* 3D Printed */}
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-black uppercase tracking-wider text-amber-600 bg-amber-50 px-2.5 py-1 rounded-md border border-amber-200">
                      Thermal Instability
                    </span>
                    <span className="text-xs text-slate-400 font-bold">3D-Printed FDM Plastic</span>
                  </div>
                  <h3 className="font-extrabold text-lg text-slate-900 mb-2">
                    3D-Printed PLA / PETG / Nylon
                  </h3>
                  <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mb-4">
                    Printed using filament extrusion. Layer lines create micro-grooves where liquid adhesive seeps. Under continuous 45°C–50°C nip temperatures, thermoplastic prints soften, warp, and delaminate along layer boundaries.
                  </p>
                </div>
                <ul className="text-xs space-y-2 text-amber-800 font-semibold border-t border-slate-200 pt-4">
                  <li>✕ Dimensional tolerance: ±0.20 mm (Stepped layers)</li>
                  <li>✕ Softens and warps above 50°C nip friction</li>
                  <li>✕ Porous voids trap isocyanate crystals</li>
                </ul>
              </div>

              {/* ImageTech CNC Virgin PTFE */}
              <div className="bg-blue-50/50 p-6 rounded-2xl border border-blue-200 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-black uppercase tracking-wider text-emerald-700 bg-emerald-100/70 px-2.5 py-1 rounded-md border border-emerald-200">
                      OEM Grade
                    </span>
                    <span className="text-xs text-blue-600 font-bold">ImageTech 5-Axis CNC</span>
                  </div>
                  <h3 className="font-extrabold text-lg text-slate-900 mb-2">
                    Virgin PTFE Teflon Dams
                  </h3>
                  <p className="text-xs sm:text-sm text-slate-700 leading-relaxed mb-4">
                    Precision CNC-machined from solid virgin fluoropolymer billets. Micro-milled to exact CAD curves with ±0.02 mm concentricity. 100% solid non-porous structure impervious to heat up to 260°C and all industrial solvents.
                  </p>
                </div>
                <ul className="text-xs space-y-2 text-emerald-800 font-semibold border-t border-blue-200 pt-4">
                  <li>✓ Dimensional tolerance: ±0.02 mm (Mirror fit)</li>
                  <li>✓ Service life: 6 to 12 months continuous running</li>
                  <li>✓ 100% safe for chrome rolls and rubber sleeves</li>
                </ul>
              </div>
            </div>
          </section>

          {/* SECTION 7: Total Cost of Ownership (TCO) & Payback Analysis */}
          <section className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm">
            <div className="max-w-3xl mb-8">
              <span className="text-xs font-black uppercase tracking-widest text-blue-600">
                Economic Payback & ROI
              </span>
              <h2 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight mt-1">
                Total Cost of Ownership (TCO) & Payback Analysis
              </h2>
              <p className="text-slate-600 text-sm sm:text-base mt-2">
                A pair of low-grade side seals might seem cheap at first glance, but edge leakage, cylinder damage, and downtime cost converting plants tens of thousands every year. Here is the realistic pressroom financial comparison.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 text-center">
                <span className="text-xs font-bold uppercase text-slate-500">Adhesive Waste Saved</span>
                <div className="text-3xl font-black text-emerald-600 my-2">₹2,80,000+</div>
                <div className="text-xs text-slate-500 font-semibold mb-2">($3,400 USD / Year)</div>
                <p className="text-xs text-slate-600 leading-relaxed">
                  Eliminates 1.5 to 2.5 kg of spilled polyurethane resin per shift that normally drips into catch pans and solidifies.
                </p>
              </div>

              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 text-center">
                <span className="text-xs font-bold uppercase text-slate-500">Cylinder Re-Chroming Saved</span>
                <div className="text-3xl font-black text-blue-600 my-2">₹8,50,000+</div>
                <div className="text-xs text-slate-500 font-semibold mb-2">($10,200 USD / Year)</div>
                <p className="text-xs text-slate-600 leading-relaxed">
                  Prevents abrasive cylinder scoring and rubber sleeve edge delamination caused by rough felt or hardened plastic blocks.
                </p>
              </div>

              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 text-center">
                <span className="text-xs font-bold uppercase text-slate-500">Press Uptime Gained</span>
                <div className="text-3xl font-black text-indigo-600 my-2">140+ Hours</div>
                <div className="text-xs text-slate-500 font-semibold mb-2">(Annual Production Capacity)</div>
                <p className="text-xs text-slate-600 leading-relaxed">
                  No more stopping the lamination line mid-job every 2 hours to scrape dried resin crusts off the cylinder ends.
                </p>
              </div>
            </div>

            <div className="p-5 rounded-2xl bg-gradient-to-r from-emerald-50 to-blue-50 border border-emerald-200 text-xs sm:text-sm text-slate-800 leading-relaxed flex flex-col sm:flex-row items-center justify-between gap-4">
              <div>
                <strong className="text-emerald-900 font-extrabold block text-base">7-Day Full Payback Period</strong>
                <span className="text-slate-600">
                  Investing in precision ImageTech CNC Teflon dams fully recovers its purchase cost in less than one week of high-speed solventless converting.
                </span>
              </div>
              <button
                onClick={() => window.dispatchEvent(new CustomEvent("open-quote-modal"))}
                className="shrink-0 bg-emerald-700 hover:bg-emerald-600 text-white font-bold px-6 py-2.5 rounded-full transition-colors cursor-pointer text-xs"
              >
                Calculate Your Plant ROI →
              </button>
            </div>
          </section>

          {/* Quick Engineering Assistance Banner */}
          <section className="bg-gradient-to-r from-blue-600 to-indigo-700 rounded-3xl p-8 sm:p-12 text-white shadow-xl flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="max-w-2xl">
              <span className="text-xs font-bold tracking-widest uppercase text-blue-200">
                Custom Engineering Assistance
              </span>
              <h2 className="text-2xl sm:text-3xl font-black mt-2 leading-tight">
                Need Exact Custom Teflon Dams for Your Machine?
              </h2>
              <p className="text-blue-100 text-sm sm:text-base mt-3 leading-relaxed">
                Send us your roller diameters, machine drawings, or a worn sample. Our CNC toolmakers machine replacement Teflon dams with 0.02 mm tolerances and rapid PAN India / global delivery.
              </p>
            </div>
            <div className="shrink-0 flex flex-col sm:flex-row gap-3 w-full md:w-auto">
              <button
                onClick={() => window.dispatchEvent(new CustomEvent("open-quote-modal"))}
                className="bg-white hover:bg-slate-100 text-blue-700 font-bold text-sm px-6 py-3.5 rounded-full transition-colors text-center shadow-md cursor-pointer"
              >
                Get Sizing & Quote →
              </button>
              <Link
                to="/troubleshooting-guide"
                className="bg-blue-800/80 hover:bg-blue-800 text-white font-bold text-sm px-6 py-3.5 rounded-full transition-colors text-center border border-blue-400/30"
              >
                Troubleshooting Guide
              </Link>
            </div>
          </section>
        </div>

        {/* SECTION 5: FAQs - Standard Full-Width UI matching all pages */}
        <FAQSection
          title="Teflon Dam Sizing & Selection FAQs"
          subtitle="Frequently Asked Questions"
          description="Find answers to common questions about sizing, measuring, and selecting precision Teflon Dams for solventless lamination machines."
          faqs={faqs}
          hideSchema={true}
        />

        {/* Universal Call to Action */}
        <HomeCTA />
      </main>
    </>
  );
}
